### ISSUE TITLE
Newb here, but where would I place the yaml code to get it to start backing up?

### ISSUE THREAD

**Issue by KnoxVegas** [matthewhadley/homeassistant-dropback#17]
Hey! Pretty new to HA, but I would love to use this. I was reading the docs, got it installed and setup, but I got to the later part about adding the yaml info. Do I need to add this to the scripts.yaml, or configuration.yaml file? I guess I'm a little confused on where to add this.

I went to add the following to the scripts.yaml and get the following error. I'm a complete newb with yaml, so maybe I just have it formatted wrong or something?
```
alias: Turn Off My Room Lights
sequence:
  - service: light.turn_off
    target:
      entity_id:
        - light.1  
        - light.2
        - light.3
        - light.4
        - light.5
mode: single

alias: System Backup To Dropbox
description: ""
triggers:
  - at: "03:00:00"
    trigger: time
actions:
  - data:
      name: "{{ now().strftime('%Y-%m-%d') }}"
    action: hassio.backup_full
  - data:
      addon: 719b45ef_dropback
      input: sync
    action: hassio.addon_stdin
mode: single

```
Here is the error code, I would assume its based on the alias part since I have something else here too with another alias name setup.
```
duplicated mapping key (13:1)

 10 |         - light.under_desk_light
 11 | mode: single
 12 | 
 13 | alias: System Backup To Dropbox
------^
 14 | description: ""
 15 | triggers:
```
